# Generated by Django 5.1.7 on 2025-03-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_issued_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceclaim',
            old_name='medical_record',
            new_name='medical_record_id',
        ),
        migrations.RenameField(
            model_name='insuranceclaim',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='medical_record',
            new_name='record_id',
        ),
    ]
