# Generated by Django 5.1.7 on 2025-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
