# Generated by Django 5.1.7 on 2025-04-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_user_notification_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('LabResult', 'LabResult'), ('General', 'General')], default='Appointment', max_length=20),
        ),
    ]
